server:
  port: 8077
spring:
  application:
    name: win-provider-server
    #配置中心客户端设置
  cloud:
    config:
      discovery:
        enabled: true
        service-id: win-eureka-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://${win-eureka.hostname}:${win-eureka.port}/eureka/

#自定义属性，配置注册中心地址
win-eureka:
  port: 8092
  hostname: 127.0.0.1
